name: Deploy ZIP to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy ZIP a Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: primer-intento-practica2            # 👈 cambia esto por el nombre real
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Practica2.zip                 # 👈 asegúrate de que la ruta es correcta
